function [bool] = checkPoseCommandValidity(prev_time,rosout_data,iiwaState,m)
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here
    if strcmp("invalid pose command", rosout_data.Msg) && prev_time ~= rosout_data.Header.Stamp.Sec && ~strcmp(rosout_data.Msg,"Loaded gazebo_ros_control.")
        bool = false; % invalid
        disp("Invalid pose command-ros")
%     elseif ~(strcmp(num2str(iiwaState.Pose.Position.X,"%.1f")...
%             ,num2str(m.Pose.Position.X,"%.1f")) ... 
%             && strcmp(num2str(iiwaState.Pose.Position.Y,"%.1f")...
%             ,num2str(m.Pose.Position.Y,"%.1f"))    ...
%              && strcmp(num2str(iiwaState.Pose.Position.Z,"%.1f")...
%             ,num2str(m.Pose.Position.Z,"%.1f"))    ...
%                 )
%     elseif ~(strcmp(num2str(iiwaState.Pose.Position.X,"%.1f")...
%             ,num2str(m.Pose.Position.X,"%.1f")) ... 
%             && strcmp(num2str(iiwaState.Pose.Position.Y,"%.1f")...
%             ,num2str(m.Pose.Position.Y,"%.1f"))...
%             )ro
    elseif ~(strcmp(num2str(iiwaState.Pose.Position.X,"%.1f")...
            ,num2str(m.Pose.Position.X,"%.1f")) ...
            )
        if str2num(num2str(iiwaState.Pose.Position.X,"%.1f")) == str2num(num2str(m.Pose.Position.X,"%.1f"))
            bool = true; % valid (-0.0 == 0.0 true)
        else
            bool = false; % invalid
            disp("Invalid pose command-false solution")
        end
        
    else
        bool = true; % valid
    end

end